/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Dao.UsuarioDao;
import Models.Cadastro;
import br.com.parg.viacep.CEP;
import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno 63
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private Cadastro cadastro;
    
    public TelaPrincipal() {
        initComponents();
        cadastro = new Cadastro();
    }
    
    public void exportarDados(Cadastro model){
       if(model.getDsNome().equals("")){
           
       } else {
          nmNomeInput.setText(model.getDsNome());
          nrCpfInput.setText(model.getDsCpf());
          cbSexo.setSelectedItem(model.getDsSexo());
          dsEmailInput.setText(model.getDsEmail());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        nmNomeInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nrCpfInput = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox<>();
        cbTipoCadastro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dsEmailInput = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        dsCepInput = new javax.swing.JTextField();
        dsBairroInput = new javax.swing.JTextField();
        dsRuaInput = new javax.swing.JTextField();
        dsUfInput = new javax.swing.JTextField();
        dsCidadeInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb01 = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        abrirTelaBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("Nome");

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        foto.setBackground(new java.awt.Color(204, 204, 204));
        foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nmNomeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmNomeInputActionPerformed(evt);
            }
        });
        nmNomeInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nmNomeInputKeyPressed(evt);
            }
        });

        jLabel3.setText("CPF");

        nrCpfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrCpfInputActionPerformed(evt);
            }
        });
        nrCpfInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nrCpfInputKeyPressed(evt);
            }
        });

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });
        cbSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbSexoKeyPressed(evt);
            }
        });

        cbTipoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Aluno" }));
        cbTipoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoCadastroActionPerformed(evt);
            }
        });
        cbTipoCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbTipoCadastroKeyPressed(evt);
            }
        });

        jLabel4.setText("Email");

        dsEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsEmailInputActionPerformed(evt);
            }
        });
        dsEmailInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dsEmailInputKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        dsCepInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dsCepInputFocusLost(evt);
            }
        });
        dsCepInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsCepInputActionPerformed(evt);
            }
        });

        dsBairroInput.setEditable(false);
        dsBairroInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsBairroInputActionPerformed(evt);
            }
        });

        dsRuaInput.setEditable(false);
        dsRuaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsRuaInputActionPerformed(evt);
            }
        });

        dsUfInput.setEditable(false);
        dsUfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsUfInputActionPerformed(evt);
            }
        });

        dsCidadeInput.setEditable(false);

        jLabel5.setText("CEP");

        jLabel6.setText("Bairro");

        jLabel7.setText("Rua");

        jLabel8.setText("UF");

        jLabel9.setText("Cidade");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tb01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Cidade", "Email", "Cpf", "CEP", "Bairro", "Rua", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb01MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb01);
        if (tb01.getColumnModel().getColumnCount() > 0) {
            tb01.getColumnModel().getColumn(0).setPreferredWidth(5);
            tb01.getColumnModel().getColumn(8).setPreferredWidth(5);
        }

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Salvar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        abrirTelaBtn.setText("Abrir Tela");
        abrirTelaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(dsUfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(dsCepInput, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abrirTelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(dsCidadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dsBairroInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(dsRuaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dsCepInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dsRuaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28))
                    .addComponent(dsBairroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dsCidadeInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dsUfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir)
                            .addComponent(btnAlterar)
                            .addComponent(btnCadastrar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(abrirTelaBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel10.setText("Sexo");

        jLabel11.setText("Tipo Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(330, 659, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nrCpfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(cbTipoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addContainerGap())
                                    .addComponent(dsEmailInput)))
                            .addComponent(nmNomeInput)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nmNomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nrCpfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dsEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nmNomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmNomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmNomeInputActionPerformed

    private void nrCpfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrCpfInputActionPerformed
        // TODO add your handling code here:
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
  //          cbSexo.requestFocusInWindow();
   //     }
    }//GEN-LAST:event_nrCpfInputActionPerformed

    private void dsRuaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsRuaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsRuaInputActionPerformed

    private void dsUfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsUfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsUfInputActionPerformed

    private void dsBairroInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsBairroInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsBairroInputActionPerformed

    private void fotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotoMouseClicked
        // TODO add your handling code here:
        
        JFileChooser NewFoto = new JFileChooser();
        NewFoto.setDialogTitle("Selecione uma Imagem");
        NewFoto.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int op = NewFoto.showOpenDialog(this);
        if(op == JFileChooser.APPROVE_OPTION){
            File file = new File("");
            file = NewFoto.getSelectedFile();
            String NomeArquivo = file.getAbsolutePath();
            ImageIcon imagem = new ImageIcon(file.getPath());
            foto.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_fotoMouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        try
        { 
          cadastro.setDsNome(nmNomeInput.getText());
          cadastro.setDsCpf(nrCpfInput.getText());
          cadastro.setDsRua(dsRuaInput.getText());
          cadastro.setDsBairro(dsBairroInput.getText());
          cadastro.setDsUf(dsUfInput.getText());
          cadastro.setDsCidade(dsCidadeInput.getText());
          cadastro.setDsSexo(cbSexo.getSelectedIndex());
          cadastro.setDsEmail(dsEmailInput.getText());
          cadastro.setDsCep(dsCepInput.getText());
          
          UsuarioDao usuarioDao = new UsuarioDao();
          boolean flSucesso = usuarioDao.inserir(cadastro);
          
          if(flSucesso == false) 
              JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL SALVAR!", "ERRO!", ERROR_MESSAGE);
          else 
              JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso!");
           
          atualizar(usuarioDao);
          limparInputs();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tb01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb01MouseClicked
        cadastro.setIdCadastro(Integer.parseInt(tb01.getValueAt(tb01.getSelectedRow(), 0).toString()));
        
        if(tb01.getValueAt(tb01.getSelectedRow(), 1) != null)
            nmNomeInput.setText(tb01.getValueAt(tb01.getSelectedRow(), 1).toString());
        
        if(tb01.getValueAt(tb01.getSelectedRow(), 2) != null)
            dsCidadeInput.setText(tb01.getValueAt(tb01.getSelectedRow(), 2).toString());
        
        if(tb01.getValueAt(tb01.getSelectedRow(), 3) != null)
            dsEmailInput.setText(tb01.getValueAt(tb01.getSelectedRow(), 3).toString());
        
        if(tb01.getValueAt(tb01.getSelectedRow(), 4) != null)
            nrCpfInput.setText(tb01.getValueAt(tb01.getSelectedRow(), 4).toString());
        
        if(tb01.getValueAt(tb01.getSelectedRow(), 5) != null)
            dsCepInput.setText(tb01.getValueAt(tb01.getSelectedRow(), 5).toString());
        
        if(tb01.getValueAt(tb01.getSelectedRow(), 6) != null)
            dsBairroInput.setText(tb01.getValueAt(tb01.getSelectedRow(), 6).toString());
        
        if(tb01.getValueAt(tb01.getSelectedRow(), 7) != null)
            dsRuaInput.setText(tb01.getValueAt(tb01.getSelectedRow(), 7).toString());
                    
        if(tb01.getValueAt(tb01.getSelectedRow(), 8) != null)
            dsUfInput.setText(tb01.getValueAt(tb01.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_tb01MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        atualizar(new UsuarioDao());
        
    }//GEN-LAST:event_formWindowOpened

    private void dsCepInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsCepInputActionPerformed
        // TODO add your handling code here:
    //    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
    //        CepInput.requestFocusInWindow();
    //    }
    }//GEN-LAST:event_dsCepInputActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try
        {
           int linhaselecionada = tb01.getSelectedRow();

           if(linhaselecionada == -1){
               JOptionPane.showMessageDialog(null,"Selecione algo para excluir");
           }else{
                int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar a consulta?");
                
                if(opcao == 0){
                    UsuarioDao usuarioDao = new UsuarioDao();
                    usuarioDao.Excluir(cadastro.getIdCadastro());

                    atualizar(usuarioDao);
                    limparInputs();
                }
           }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        new Thread(){
            @Override
            public void run(){
                try
                {
                    cadastro.setDsNome(nmNomeInput.getText());
                    cadastro.setDsCpf(nrCpfInput.getText());
                    cadastro.setDsRua(dsRuaInput.getText());
                    cadastro.setDsBairro(dsBairroInput.getText());
                    cadastro.setDsUf(dsUfInput.getText());
                    cadastro.setDsCidade(dsCidadeInput.getText());
                    cadastro.setDsSexo(cbSexo.getSelectedIndex());
                    cadastro.setDsEmail(dsEmailInput.getText());
                    cadastro.setDsCep(dsCepInput.getText());

                    UsuarioDao usuarioDao = new UsuarioDao();
                    usuarioDao.alterar(cadastro);

                    limparInputs();
                    atualizar(usuarioDao);
                }catch(Exception ex){
                   JOptionPane.showMessageDialog(null,ex.getMessage()); 
                   Thread.currentThread().interrupt();
                }
            } 
        }.start();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void dsCepInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dsCepInputFocusLost
        ViaCEP viaCep = new ViaCEP();
        
        try 
        {
           viaCep.buscar(dsCepInput.getText());  
           dsBairroInput.setText(viaCep.getBairro());
           dsRuaInput.setText(viaCep.getLogradouro());
           dsUfInput.setText(viaCep.getUf());
           dsCidadeInput.setText(viaCep.getLocalidade());
        }
        catch(ViaCEPException ex) {
            // Cassio socorrer depois
            JOptionPane.showMessageDialog(null, ex.getMessage(), "socorro!!!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dsCepInputFocusLost

    private void abrirTelaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaBtnActionPerformed
          TelaCadastro telaCadastro = new TelaCadastro();
        
          telaCadastro.cadastro.setDsNome(nmNomeInput.getText());
          telaCadastro.cadastro.setDsCpf(nrCpfInput.getText());
          telaCadastro.cadastro.setDsRua(dsRuaInput.getText());
          telaCadastro.cadastro.setDsBairro(dsBairroInput.getText());
          telaCadastro.cadastro.setDsUf(dsUfInput.getText());
          telaCadastro.cadastro.setDsCidade(dsCidadeInput.getText());
          telaCadastro.cadastro.setDsSexo(cbSexo.getSelectedIndex());
          telaCadastro.cadastro.setDsEmail(dsEmailInput.getText());
          telaCadastro.cadastro.setDsCep(dsCepInput.getText());
          
          telaCadastro.setVisible(true);
    }//GEN-LAST:event_abrirTelaBtnActionPerformed

    private void nmNomeInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmNomeInputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            nrCpfInput.requestFocusInWindow();
        }
    }//GEN-LAST:event_nmNomeInputKeyPressed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_cbSexoActionPerformed

    private void cbTipoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoCadastroActionPerformed
        // TODO add your handling code here:
     
    
    }//GEN-LAST:event_cbTipoCadastroActionPerformed

    private void dsEmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsEmailInputActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_dsEmailInputActionPerformed

    private void dsEmailInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dsEmailInputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            dsCepInput.requestFocusInWindow();
        }
    }//GEN-LAST:event_dsEmailInputKeyPressed

    private void nrCpfInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nrCpfInputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cbSexo.requestFocusInWindow();
        }
    }//GEN-LAST:event_nrCpfInputKeyPressed

    private void cbSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSexoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cbTipoCadastro.requestFocusInWindow();
        }
    }//GEN-LAST:event_cbSexoKeyPressed

    private void cbTipoCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTipoCadastroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            dsEmailInput.requestFocusInWindow();
        }
    }//GEN-LAST:event_cbTipoCadastroKeyPressed

     private void atualizar(UsuarioDao usuarioDao)
    {
        try
        {
            limpartabela();
            
            ArrayList<Cadastro> listaCadastros;
            listaCadastros = usuarioDao.consultar(); 
            
            DefaultTableModel modeloTabela = (DefaultTableModel) tb01.getModel();
            
            for(Cadastro cadastro : listaCadastros)
            {
                modeloTabela.addRow(new String[]{Integer.toString(cadastro.getIdCadastro()), cadastro.getDsNome(), cadastro.getDsCidade(), cadastro.getDsEmail(), cadastro.getDsCpf(), cadastro.getDsCep(), cadastro.getDsBairro(), cadastro.getDsRua(), cadastro.getDsUf()});
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
        }
    }
    private void limpartabela(){
        while(tb01.getRowCount() > 0){
            DefaultTableModel DTM = (DefaultTableModel) tb01.getModel();
            DTM.getDataVector().removeAllElements();
        }
            
    }
    private void limparInputs(){
        nmNomeInput.setText("");
        dsEmailInput.setText("");
        nrCpfInput.setText("");
        dsCepInput.setText("");
        dsBairroInput.setText("");
        dsRuaInput.setText("");
        dsUfInput.setText("");
        dsCidadeInput.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirTelaBtn;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cbTipoCadastro;
    private javax.swing.JTextField dsBairroInput;
    private javax.swing.JTextField dsCepInput;
    private javax.swing.JTextField dsCidadeInput;
    private javax.swing.JTextField dsEmailInput;
    private javax.swing.JTextField dsRuaInput;
    private javax.swing.JTextField dsUfInput;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nmNomeInput;
    private javax.swing.JTextField nrCpfInput;
    private javax.swing.JTable tb01;
    // End of variables declaration//GEN-END:variables
}
